from . import sale_order
from . import product_template
from . import purchase_order
from . import product_product
from . import warehoues_orderpoint
from . import stock_quant
from . import stock_move
from . import cells_terms
from . import res_config